### ISSUE TITLE
Can't instal with LspInstall

### ISSUE THREAD

**Issue by michalens** [mattn/efm-langserver#105]
I am running `:LspIstall eft` and getting the following error

```
package github.com/mattn/efm-langserver@HEAD: invalid github.com/ import path "github.com/mattn/efm
-langserver@HEAD"

[Process exited 1]
```

**Comment by mattn** [comment]
What is the command LspInstall?

**Comment by michalens** [comment]
It's coming from https://github.com/kabouzeid/nvim-lspinstall

Should I open an issue there?

**Comment by mattn** [comment]
It is an issue of nvim-lspinstall.

https://github.com/kabouzeid/nvim-lspinstall/blob/dbb8261b272e6c5f67af1f02d6bacd347f8f9520/lua/lspinstall/servers/efm.lua#L7

This should not use HEAD. Please file new issue for nvim-lspinstall.

**Comment by kabouzeid** [comment]
Is there another way to install a release with (https://github.com/mattn/efm-langserver/pull/93) merged? Otherwise the slow exit of nvim caused by efm (https://github.com/mattn/efm-langserver/issues/94) is a huge annoyance :/

**Comment by mattn** [comment]
Now fixed build on Go1.11.
