### ISSUE TITLE
Give filepath to lint-command when lint-stdin is false

### ISSUE THREAD

**Issue by hisaknown** [mattn/efm-langserver#12]
When `lint-stdin` is `false` in config, the lint command should take the path to an input file as an argument.  
But for now, the lint command is called without the filepath, while `lint-stdin` is `false`.

I'm not familiar with golang, but following patch seems to work for me.  
(Just adding filename at the end of the lint command.)

```diff
--- a/langserver/handler.go
+++ b/langserver/handler.go
@@ -157,11 +157,17 @@ func (h *langHandler) lint(uri string) []Diagnostic {

        diagnostics := []Diagnostic{}

+    var lintfname string
+       if !config.LintStdin {
+               lintfname = " " + fname
+       } else {
+               lintfname = ""
+       }
        var cmd *exec.Cmd
        if runtime.GOOS == "windows" {
-               cmd = exec.Command("cmd", "/c", config.LintCommand)
+               cmd = exec.Command("cmd", "/c", config.LintCommand+lintfname)
        } else {
-               cmd = exec.Command("sh", "-c", config.LintCommand)
+               cmd = exec.Command("sh", "-c", config.LintCommand+lintfname)
        }
        if config.LintStdin {
                cmd.Stdin = strings.NewReader(f.Text)
```

Or, providing a placeholder for the filepath in the config file (like `lint-command: 'some-lint-command %s'`, `%s` will be replaced with the filepath) might be more elegant.

Note: I'd like to use [`redpen`](https://github.com/redpen-cc/redpen) with `efm-langserver`. `redpen` does not accept stdin as an input.

**Comment by mattn** [comment]
Thanks. Could you please try last change?

**Comment by hisaknown** [comment]
Thank you for the fix.

But there seems to be a typo, and does not work out of the box:
https://github.com/mattn/efm-langserver/blob/97c3771e3050aa85aecf05027a488dfe5a2762e4/langserver/handler.go#L151

Replacing `SymbolCommand` to `LintCommand`, it worked for me.

**Comment by mattn** [comment]
Thanks. Fixed.

**Comment by mattn** [comment]
Please reoepn if you still have an issue. Thanks.
