### ISSUE TITLE
How to disable efm log sent to lsp?

### ISSUE THREAD

**Issue by ray-x** [mattn/efm-langserver#122]
efm seems send logs to stderr of nevim lsp/rpc.lua
So each keystroke will generate a logs item. 
e.g
[ ERROR ] 2021-05-02T00:35:26+1000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"efm-langserver"	"stderr"	"2021/05/02 00:35:26 lint for LanguageID not supported: \n"

How to disable this?

**Comment by cloggier** [comment]
Related #87

**Comment by mattn** [comment]
Closed by https://github.com/mattn/efm-langserver/commit/fb9bc0c5f3c39fea39611dd87431c35c982ee780
