### ISSUE TITLE
completion for LanguageID not supported

### ISSUE THREAD

**Issue by AtomToast** [mattn/efm-langserver#128]
I am using nvims builtin lsp with nivm-lspconfig and nvim-compe.
For some reason pretty much everytime I close a file I get an error message saying

```Client 1 quit with exit code 2 and signal 0%```

When looking at the log I can see that whenever I start typing things there are errors like this generated on every keystroke:

```[ ERROR ] 2021-05-17T15:12:34+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]  "rpc"   "efm-langserver"        "stderr"  "2021/05/17 15:12:34 completion for LanguageID not supported: json\n"```

(in this case I have am editing a json file but it also happens for other filetypes)

This is the relevant part of my lsp config:
```lua
lspconfig.efm.setup{
  init_options = {documentFormatting = true},
  filetypes = {
    ...
    "json",
    ...
  },
  settings = {
    rootMarkers = {".git/"},
    languages = {
      ...
      json = {
        {
          formatCommand = "prettier ${--tab-width:tabWidth} --parser json",
          lintCommand = "jq .",
          lintStdin = true,
        },
      },
      ...
    }
  }
}
```

you can find my entire lsp config [here](https://github.com/AtomToast/dotfiles/blob/master/.config/nvim/config/plugins/nvim-lspconfig.vim)

I have pulled my hair out over this for hours now trying to figure out why efm-langserver tries to offer completion but I just can't figure it out. Any help would be greatly appreciated. Let me know if you need any additional info

**Comment by mattn** [comment]
Closed by https://github.com/mattn/efm-langserver/commit/fb9bc0c5f3c39fea39611dd87431c35c982ee780
