### ISSUE TITLE
[Duplicated] "Client 2 quit with exit code 2 and signal 0"

### ISSUE THREAD

**Issue by kdav5758** [mattn/efm-langserver#129]
First of all, yes, this is a duplicated, but since the other issue hasn't been solved and seems "inactive" since the last 9 days, thought I'd report it again to give it mode attention. My problem is the same one as described in the issue #127. What's happening is that:

1. After quitting, Lang server is not shutting down properly
2. NVim sees that its exit code was != 0
3. Nvim reports the error (`Client 2 quit with exit code 2 and signal 0` in this case) using [this](https://github.com/mjlbach/neovim/blob/21035cff9f1d279e3cb5ec866916bfa231cdbaa2/runtime/lua/vim/lsp.lua#L738-L743)

My question is: While this is being solved, how could I suppress those error messages?

**Comment by mjlbach** [comment]
You're asking on the wrong issue tracker, EFM isn't printing the exit code, neovim is. I've already given you some pointers on writing a filter over vim.notify via DM on reddit, post on reddit, etc. You'll have to refine that snippet until it works for you.

**Comment by kdav5758** [comment]
Latest commit seems to have fixed it.
