### ISSUE TITLE
Lint whole project instead of file

### ISSUE THREAD

**Issue by gowep** [mattn/efm-langserver#143]
I am setting up neovim builtin lsp with efm and wanted to use go linters. The problem is that a lot of them print false warnings when linting only a file instead of a whole project.
Is there any way I can set a linter to lint the whole project?

**Comment by ahmedkhalf** [comment]
Same issue here, please let me know if you fixed it

**Comment by gegoune** [comment]
It sounds like linter's configuration issue.

**Comment by gowep** [comment]
I am using staticcheck with this configuration: 
```
return {
    lintCommand = "staticcheck",
    lintFormats = {"%f:%l:%c: %m"},
    lintSource = "staticcheck",
    lintSeverity = 2
}
```
The problem is that I get a lot of warning like "undeclared name" in files because structs are defined in a different file. There is not a single warning if I lint the whole project with `staticcheck ./...`. How to fix this?
