### ISSUE TITLE
Add support for prefix or sourceName

### ISSUE THREAD

**Issue by rostero1** [mattn/efm-langserver#145]
With multiple language servers and linters it makes it hard to see where where an error is coming from.  It would be great if efm-langserver could support a `prefix` or `sourceName`.

```
local eslintLint = {
  prefix = "[eslint]"
  lintCommand = "./node_modules/.bin/eslint -f visualstudio --stdin --stdin-filename ${INPUT}",
  lintIgnoreExitCode = true,
  lintStdin = true,
  rootMarkers = {"package.json"},
  lintFormats = {
    "%f(%l,%c): %tarning %m",
    "%f(%l,%c): %rror %m"
  }
}
```

Would show in the fix list (or hover) as 
```
[eslint] react-hooks/exhaustive-deps : React ...
```

Creating a custom formatter isn't great with eslint and so having this as an `efm` option is ideal in this situation.

**Comment by mattn** [comment]
Closed by https://github.com/mattn/efm-langserver/pull/148
