### ISSUE TITLE
Is there a way to set init_options per language?

### ISSUE THREAD

**Issue by JRasmusBm** [mattn/efm-langserver#155]
Thank you so much for an amazing project 🎉

I have a question. When connecting to a language server in Neovim it is very important to know what functionality it supports, so that mappings can be made to i.e. format the document. If the language server does not support that functionality, I want to fall back to a custom, more generic formatting solution. 

The problem arises when I have configured efm-langserver to have different capabilities for each language. Is there a way to tell efm / neovim what filetypes the langserver supports, so that the fallback is enabled for some language, and the lsp-formatting is enabled for others?

Thank you so much in advance 😄

**Comment by alexaandru** [comment]
I haven't tried `init_options` myself, but I handled it from the `on_attach` handler: https://github.com/alexaandru/nvim-config/blob/master/lua/config/efm.lua#L72-L73  Works like a charm, `efm` only advertises formatting for the languages that actually have a format command defined.

**Comment by JRasmusBm** [comment]
That's an acceptable workaround, thank you! 😄

**Comment by alexaandru** [comment]
You're most welcome! :)
