### ISSUE TITLE
I can't any error message for init.vim

### ISSUE THREAD

**Issue by steelbluelee** [mattn/efm-langserver#16]
I set up efm-langserver according to the readme in this repository and tested with init.vim file
which has errors. But I can't any error messages. I checked that the efm-langserver start successfully.
But, I can't see any messages from vim-vint.

What do I examine to solve this problem?

**Comment by mattn** [comment]
What language server client do you use?

**Comment by steelbluelee** [comment]
I'm using coc.nvim.

thx

**Comment by mattn** [comment]
Which way to install vim-vint?

**Comment by mattn** [comment]
If you use pip to install vint, please try this.

```
vim:
  lint-command: 'vint'
  lint-stdin: false
```

**Comment by steelbluelee** [comment]
Your comments didn't solve my problem, but gave me a hint why vim-vint doesn't work.
I'm going to try in other ways.

thx.

**Comment by mattn** [comment]
Please try with `-` .

```
  vim:
    lint-command: 'vint -'
    lint-stdin: true
```
