### ISSUE TITLE
[Question] Is it possible to achieve range formatting?

### ISSUE THREAD

**Issue by rebelot** [mattn/efm-langserver#177]
I mainly code in python and cpp, lua occasionally to edit neovim config
Is it possible to achieve range formatting in neovim?
I use nvim native lsp with lspconfig.

**Comment by olekthunder** [comment]
It seems that you can't.

According to the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/), you have to send `textDocument/rangeFormatting` request, which is not handled by this server:
https://github.com/mattn/efm-langserver/blob/6b320aea1c0c7aba2059458addd0976a28c43783/langserver/handler.go#L621-L658

**Comment by llllvvuu** [comment]
Solution is here: https://github.com/mattn/efm-langserver/pull/246
