### ISSUE TITLE
publishDiagnostics is no longer sent when there are no diagnostics

### ISSUE THREAD

**Issue by fsouza** [mattn/efm-langserver#197]
Looks like this is a regression caused by #193. Example workflow with Python and flake8 (could be anything really):

1. I make a change in the editor. flake8 won't be happy with this change
2. Editor sends `textDocument/didChange` to efm
3. efm runs flake8, gets the error, build the list of diagnostics and invoke `textDocument/publishDiagnostics`
4. Editor renders the errors, I fix the error and the editor sends `textDocument/didChange` to efm
5. efm runs flake8, gets no errors and don't send `textDocument/publishDiagnostics`
6. Editor continues to display the error message

On step 5, efm should send `textDocument/publishDiagnostics` with an empty list of diagnostics, but instead it simply doesn't send the notification.

**Comment by fsouza** [comment]
Sent #198. Let me know what you think.

**Comment by ayamir** [comment]
Seems like not fully fix it?

https://user-images.githubusercontent.com/61657399/148958118-15e1c7e3-57ab-49a5-8b3b-ca20e0982406.mp4
