### ISSUE TITLE
ignore formatting for certain paths

### ISSUE THREAD

**Issue by delfick** [mattn/efm-langserver#202]
Hello,

Is it possible to make it so that a formatter doesn't run under certain paths?

For example, if I'm editing a file in a python virtualenv site-packages folder I'd rather it didn't call black on that file.

I can use root-markers to look for a file in my project so that I can prevent this for say a python installation, but this doesn't work for any virtualenvs in my project.

**Comment by mattn** [comment]
Are you setting up formatter with saving?

**Comment by delfick** [comment]
yes correct. I like my editor to run the formatter on save.
