### ISSUE TITLE
Hover word charactor white list configuration

### ISSUE THREAD

**Issue by Matts966** [mattn/efm-langserver#206]
Add `hover-char` option for splitting words for hover information.

To keep compatibility, we can use `_` as the default setting.

**Comment by mattn** [comment]
Could you please explain your use case?

**Comment by Matts966** [comment]
@mattn 
For example, I want to use `.` as `hover-char` to get keywords such as `a.method` and `schema.table`.

**Comment by mattn** [comment]
efm-langserver does not provide way to key assign for the text editor. You need to setup your text editor to call hover.

**Comment by mattn** [comment]
Ah, do you mean this condition?

https://github.com/mattn/efm-langserver/blob/b13f35f67c84029a83d245928ef29fa40b5e1d9c/langserver/handle_text_document_hover.go#L64

**Comment by Matts966** [comment]
Yes! I mean that `char` variable!

**Comment by mattn** [comment]
I'm worried that this setting will cause hover to malfunction with ambiguous text. For example
```
Removed method foo.Bar.
```

**Comment by Matts966** [comment]
@mattn 
You are right. This setting can cause unexpected results.

However, I think it is relatively easy to validate input texts in the `hover-command` and use trimmed texts or ignore invalid texts.

This new setting will make it possible to retrieve schema of target tables, and it is easy to ignore invalid or unknown tables in that case. Showing descriptions and schema for target tables can significantly improve query writing experience. 
Also, I believe this setting can make other useful cases possible.

**Comment by mattn** [comment]
Addressed in https://github.com/mattn/efm-langserver/pull/208

**Comment by Matts966** [comment]
Thank you! It looks great!
