### ISSUE TITLE
Option to skip linting/formatting if rootMarkers can't be resolved?

### ISSUE THREAD

**Issue by fsouza** [mattn/efm-langserver#213]
Hi there!

Would you take a PR adding an option or something like that to allow linting/formatting/anything else if rootMarkers can't be resolved?

For example:

- on `textDocument/formatting`, tries to find a root dir for the command using _only_ the root markers, and if that can't be found, exit early and return the contents unchanged
- on `textDocument/didChange`, tries to find a root dir for the command using _only_ the root markers, and i f one can't be found, abort early and publish an empty array of diagnostics for the provided URI
- do something similar for all other methods (I'd make sure the solution is generic enough without replicating the check everywhere)

What do you think? Is that feasible/acceptable? Thank you!

**Comment by mattn** [comment]
What you want is that efm-langserver do NOT operating linting/formatting/anything if rootMarkers can't be found. Right?

**Comment by fsouza** [comment]
> What you want is that efm-langserver do NOT operating linting/formatting/anything if rootMarkers can't be found. Right?

Exactly. Since that would be a behavior change, I think we should do it behind a new knob. Would that be acceptable?

**Comment by mattn** [comment]
I don't think it's not breaking behavior. I think.

**Comment by mattn** [comment]
Please do

**Comment by fsouza** [comment]
Oh, looks like for linting it's already in-place: https://github.com/mattn/efm-langserver/commit/fdd0aab0e2dcc5e823feb9de170ebf036b213a0a

I can reuse the strategy and the config flag for textDocument/formatting. Will do that and open a PR
