### ISSUE TITLE
[Question] Why archlinux AUR remove this package?

### ISSUE THREAD

**Issue by WUST-mengqinyu** [mattn/efm-langserver#216]
[https://archlinux.org/packages/community/x86_64/efm-langserver/](https://archlinux.org/packages/community/x86_64/efm-langserver/)
shows: `efm-langserver 0.0.40-1 is no longer available`

**Comment by polyzen** [comment]
I had moved efm-ls into the official repos but since switched to [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim). It was moved back into the [AUR](https://aur.archlinux.org/packages/efm-langserver) so someone else could maintain it.
