### ISSUE TITLE
Improve doc for installation; the one-line go command doesn't work for me

### ISSUE THREAD

**Issue by kohane27** [mattn/efm-langserver#217]
I ran the command `go install github.com/mattn/efm-langserver@latest` but I can't get it to work: there is no output and error. I'm not familiar with Go at all. Eventually I figured out a way to install it:

1. `git clone https://github.com/mattn/efm-langserver.git`
2. `cd efm-langserver`
3. `make build`
4. move the bin `efm-langserver` to `/usr/local`
5. the command `efm-langserver` should now work

Is this the only way to install it? If yes, I'll create a pull request to update the doc.

**Comment by luisfscoelho** [comment]
I had a similar problem because I installed go with asdf.

**Comment by dzintars** [comment]
Alternative way is to download binary from [releases](https://github.com/mattn/efm-langserver/releases) and place it somewhere in the `$PATH`. For example `~/.local/bin` is a good place. But again, make sure that `~/.local/bin` is in your `$PATH`.
I believe on Windows/Mac it's the same story.

**Comment by zachliu** [comment]
i use `asdf` and i have `go1.19.4 linux/amd64`
```shell
go install github.com/mattn/efm-langserver@latest
```
does work in this version of go
golang changes a lot between versions :thinking:

**Comment by mattn** [comment]
You need add ~/go/bin to the PATH environment variable.
