### ISSUE TITLE
What is the full form of efm?

### ISSUE THREAD

**Issue by ambadyanands** [mattn/efm-langserver#227]
Sorry if this seems as an abuse of the issues section, but I don't see any other recomended places for such silly questions. So, what does `efm` in the `efm-langserver` stand for?

Thanks.

**Comment by mattn** [comment]
efm is errorformat from Vim's `efm` option. https://github.com/reviewdog/errorformat provide same feature of that.

**Comment by ambadyanands** [comment]
@mattn Thanks a lot, I did not about vim's `errorformat` option. So it was worth asking as I learned something new! :)
