### ISSUE TITLE
Vint not working

### ISSUE THREAD

**Issue by ilovehans10** [mattn/efm-langserver#25]
Using coc.vim I was noticing that the linting was not matching up with what I had received when I just ran vint on my vimrc and in fact I was not receiving any linting. I then tested what would happen if I piped from vint the langserver command (like so `vint .vimrc | efm-langserver`) and I received nothing but the two following lines.
`2020/01/15 13:00:32 efm-langserver: reading on stdin, writing on stdout`
`2020/01/15 13:00:33 efm-langserver: connections closed`

When I run vint on the file directly however I receive the following, so I know that it is not due to a lack of linting by vint.
`.vimrc:99:28: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))`
`.vimrc:143:3: autocmd should execute in an augroup or execute with a group (see :help :autocmd)`
`.vimrc:222:1: autocmd should execute in an augroup or execute with a group (see :help :autocmd)`

I am new to both coc.vim and emf-langserver and therefore could be doing something totally wrong or overlooking something obvious.

**Comment by lambdalisue** [comment]
Because of https://github.com/Vimjas/vint/issues/305

1. Install vint from git like `pip install git+https://github.com/vimjas/vint`
2. Do not use stdin like below

```yaml
  vim:
    lint-command: 'vint'
    lint-stdin: false
```
﻿

**Comment by ilovehans10** [comment]
This seems to have fixed the issue. Thanks!
