### ISSUE TITLE
Language with .(dot) in the name for neovim lsp

### ISSUE THREAD

**Issue by budimanjojo** [mattn/efm-langserver#252]
Hi, thanks for this awesome tool!

I don't think I can use something like this for my neovim with lspconfig setup:
```
require "lspconfig".efm.setup {
    init_options = {documentFormatting = true},
    settings = {
        languages = {
            yaml.ansible = {
                {lintCommand = "ansible-lint", lintStdin = true}
            }
        }
    }
}
```

The reason is because `ansible-language-server` requires the filetype to be  `ansible.yaml` to work and the plugin `pearofducks/ansible-vim` will change the filetype to be `ansible.yaml` when it detects the file is `ansible` yaml file.

**Comment by milanglacier** [comment]
you can configure this in the neovim side, see the nvim-lspconfig specs of how to use languageID options

**Comment by budimanjojo** [comment]
it works! thanks!
