### ISSUE TITLE
Don't create a force creating an `~/.config/efm-langserver` folder

### ISSUE THREAD

**Issue by chrisgrieser** [mattn/efm-langserver#259]
Thanks for this LSP, it's a great solution!

So I use nvim and the [efm-config-plugin](https://github.com/creativenull/efmls-configs-nvim), therefore, I configure efm without any `config.yaml`. However, the folder `~/.config/efm-langserver` still get created nonetheless, even though I will never have any use for it.

Could the auto-creation of the folder maybe be disabled? A setting to do so would probably already be fine.

**Comment by mattn** [comment]
Are you using `-c` flag?

**Comment by chrisgrieser** [comment]
ah yes, that solves it. thx
