### ISSUE TITLE
pylint: need configurable severity types, or default to "I" (information)

### ISSUE THREAD

**Issue by pappasam** [mattn/efm-langserver#50]
First off, I love this tool! It's got big dreams and I'd like it to keep getting better! This is issue 2 of 2 related to pylint.

pylint has additional messages types:

* [I]nformational messages that Pylint emits (do not contribute to your analysis score)
* [R]efactor for a "good practice" metric violation
* [C]onvention for coding standard violation
* [W]arning for stylistic problems, or minor programming issues
* [E]rror for important programming issues (i.e. most probably bug)
* [F]atal for errors which prevented further processing

Currently, when efm encounters an unknown message type, it defaults to the "Error" value. See current logic here: https://github.com/mattn/efm-langserver/blob/master/langserver/handler.go#L282

Example pylint error messages (0-indexed): I currently use the efm format  `%f:%l:%c: %t%m` which works well if you ignore https://github.com/mattn/efm-langserver/issues/49.

file.py:13:0: C0116: Missing function or method docstring (missing-function-docstring)
file.py:27:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
file.py:40:8: W0612: Unused variable 'response' (unused-variable)
file.py:55:4: E0102: method already defined line 36 (function-redefined)
file.py:71:4: E0602: Undefined variable 'url' (undefined-variable)
file.py:6:0: W0611: Unused Final imported from typing (unused-import)

**Comment by mattn** [comment]
@haya14busa Do you have any ideas?

**Comment by pappasam** [comment]
If it helps, diagnostic severity information is documented here: https://microsoft.github.io/language-server-protocol/specification#diagnostic

I'll tinker away at this in the meantime as well. I'm unfamiliar with golang but the code is quite readable.

**Comment by mattn** [comment]
Yes, I know the protocol. And the DiagnosticSeverity accept only 4 values.

**Comment by pappasam** [comment]
In case this helps you think through options, "diagnostic language server" handles this using the "securities" field in their server's configuration. They also have a fix for the issue I opened about column configuration as well. See my example configuration that works for pylint: https://github.com/iamcco/diagnostic-languageserver/wiki/Linters#pylint
