### ISSUE TITLE
Feature request: Debounce(delay) setting

### ISSUE THREAD

**Issue by khaveesh** [mattn/efm-langserver#65]
[diagnostic-ls](https://github.com/iamcco/diagnostic-languageserver) has an option to set debounce time which is a very useful feature in LSP programs. I regularly deal with moderate to huge size files for which the linters take more time to finish. But the efm-server cannot cope with such delays and the diagnostics flicker and disappear often. If there is an option to set the debounce time, that is the delay after which the linter is run again, I am hopeful that this problem can be resolved.

**Comment by mattn** [comment]
Do you want debounce option for each commands?

**Comment by khaveesh** [comment]
Not for each command, but just for each linter entry add an option to set the time interval in millisecond after which the linter is run again. If the entry has 500 as value, call the linter once every 500ms and so on.

**Comment by mattn** [comment]
Thank you
