### ISSUE TITLE
问下大佬 为什么我没安装成功

### ISSUE THREAD

**Issue by huayue369** [mattn/efm-langserver#7]
```
这是我的coc配置
"languageserver": {
  "golang": {
      "filetypes": ["go"],
      "command": "bingo",
      "args": ["--diagnostics-style=instant"],
      "rootPatterns": ["go.mod", ".vim/",".git/", ".hg/"]
},
  "efm": {
      "command": "efm-langserver",
      "args": [],
      "filetypes": ["vim", "eruby", "markdown"]
      }
    }
  }
```
报错信息：
<img width="846" alt="屏幕快照 2019-03-25 下午7 33 33" src="https://user-images.githubusercontent.com/32536764/54959974-dee85400-4f95-11e9-8a6b-947e8cf33478.png">

**Comment by huayue369** [comment]
<img width="1000" alt="屏幕快照 2019-03-26 上午6 41 44" src="https://user-images.githubusercontent.com/32536764/54959991-f58eab00-4f95-11e9-991e-63dd1c5cc83d.png">
不好意思 上图发送错了 是这张

**Comment by mattn** [comment]
Please write english.

**Comment by mattn** [comment]
time is up

**Comment by mattn** [comment]
As far as I can see the second screenshot, your configuration file seems to be wrong. Please try to run efm-langserver standalone.
