### ISSUE TITLE
Cannot enable linting with eslint on JS files using native nvim lsp.

### ISSUE THREAD

**Issue by stellarhoof** [mattn/efm-langserver#77]
I'm using neovim's native LSP and I'm getting `2020/11/28 08:18:39 lint for LanguageID not supported: ` on the server logs. Notice that the `LanguageID` in the logs is empty. I tried tweaking the log level via the `-loglevel` cli option with no effect. How can I debug this?

Here's my configuration for reference:

```lua 
lspconfig.efm.setup {
   cmd = {"efm-langserver", "-logfile", log_dir .. "/efm.log"},
   on_attach = on_attach(log_dir .. "/efm.log"),
   -- Fallback to .bashrc as a project root to enable LSP on loose files
   root_dir = lspconfig.util.root_pattern(".git/", ".bashrc"),
   -- Enable document formatting (other capabilities are off by default).
   init_options = {documentFormatting = true},
   settings = {
     rootMarkers = {".git/", ".bashrc"},
     languages = {
       javascript = {
        {
          lintCommand = "eslint -f unix --stdin",
          lintIgnoreExitCode = true,
          lintStdin = true,
        }
       },
     },
   },
 }
```

**Comment by mattn** [comment]
Could you please provide your config.yaml?

**Comment by stellarhoof** [comment]
Thanks for the prompt response. I don't use a `config.yaml`, I use the recently added feature for `DidChangeConfiguration`

**Comment by mattn** [comment]
What filetype did you open?

**Comment by stellarhoof** [comment]
`javascript`

**Comment by mattn** [comment]
Hmm. I'll look into it tonight.

**Comment by mattn** [comment]
I could configure with vim-lsp and vim-lsp-settings (LspSettingsEditLocal).

```json
{
	"efm-langserver": {
        "workspace_config": {
            "languages": {
                "javascript": [
                    {
                        "lintCommand": "eslint -f unix --stdin",
                        "lintIgnoreExitCode": true,
                        "lintStdin": true
                    }
                ]
            }
        }
    }
}
```

**Comment by mattn** [comment]
You can debug messages from stderr of efm-langserver.

**Comment by stellarhoof** [comment]
@mattn I don't think I can access the server's stderr since it gets spawned by nvim.

I see that @lukas-reineke added support for `DidChangeConfiguration`. I copied his example in the readme and it looks like he's also using it [on his dotfiles](https://github.com/lukas-reineke/dotfiles/blob/7eec44f99c64be1916e246ab51c1d4e4a4083670/vim/lua/lsp.lua#L293). @lukas-reineke is it working for you?

**Comment by lukas-reineke** [comment]
your config works fine for me.
Maybe `eslint` is not in your path?

**Comment by lukas-reineke** [comment]
> `LanguageID` is empty

I didn't see that at first, this sounds like your nvim LSP is not setup correctly.
can you link your config?

**Comment by stellarhoof** [comment]
Thanks for the prompt reply. `eslint` is in my path. I have `./node_modules/.bin` in `$PATH` and `eslint` is also installed globally so a bare `eslint` always resolves to the correct one. Here's the [relevant section](https://github.com/stellarhoof/furnisher/blob/master/stow/.config/nvim/lua/lsp/init.lua#L54-L113) in my dotfiles

**Comment by lukas-reineke** [comment]
I don't see anything obvious in your config.

I think know what your problem is, but I don't know why it's happening.
For some reason, Neovim doesn't resolve the `filetype` correctly when first attaching the buffer to LSP.
Afterwards efm just has an empty string as the `languageID`, and your config doesn't get resolved. This is an issue with Neovim.

I had the same thing happen as well, but I refactored a bunch of things and it went away. I never figured out what was wrong.
The place in Neovim source is not that complicated https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L281
really not sure what is causing this.

I think you can close the issue here and open one in Neovim. Or ask in the Gitter channel if someone has an idea.

**Comment by stellarhoof** [comment]
Makes sense. Thanks for the detailed reply @lukas-reineke! I'll investigate on my own and possibly open an issue on nvim.

**Comment by stellarhoof** [comment]
@mattn Actually it would be very helpful if `efm` was more chatty. At the very least send the stderr to the server's log file. Also support different log levels. I see a `-loglevel` cli option but changing it has no effect on the server log. It would be much easier to debug if I could increase the log level and see all incoming requests from nvim.

**Comment by disrupted** [comment]
@stellarhoof same issue here with the empty LanguageID and it only seems to affect some files. Did you open an issue on neovim or find out what's causing this?
