### ISSUE TITLE
Format not working

### ISSUE THREAD

**Issue by gbrlsnchs** [mattn/efm-langserver#88]
I'm using Neovim's built-in LSP support to run `./node_modules/.bin/prettier` on TypeScript files. Checking the logs, it seems to be working internally and `newText` is properly generated, and even the `format succeeded` message appears. However my files are not being formatted, and logs mention a `$cancelRequest` with the same ID of the `textDocument/formatting` request.

**Comment by mattn** [comment]
I'm not familier to nvim. Anyone could you handle this?

**Comment by remi-gelinas** [comment]
Just chiming in to say that I'm have the exact same problem, but with `loglevel` at 10, I don't get any events or requests for `textDocument/formatting` in the logfile at all. It's like `efm` doesn't even attempt to reformat anything. I can confirm the document formatting capability and prettier command are both correct in when `workspace/didChangeConfiguration` is sent though.

**Comment by lukas-reineke** [comment]
I have prettier set up fine with Neovim's LSP.
Can you both share your config, I can take a look.

**Comment by gbrlsnchs** [comment]
> I have prettier set up fine with Neovim's LSP.
> Can you both share your config, I can take a look.

Hi @lukas-reineke, thanks for your help. My config is more or less the following (I'm omitting some non-related things):

```lua
local nvim_lsp = require('lspconfig')

local on_attach = function(client)
  if client.resolved_capabilities.document_formatting then
    vim.cmd [[augroup lsp_formatting]]
    vim.cmd [[autocmd!]]
    vim.cmd [[autocmd BufWritePre <buffer> :lua vim.lsp.buf.formatting_sync()]]
    vim.cmd [[augroup END]]
  end
end

local efm_formatters = {
  prettier = {
    formatCommand = './node_modules/.bin/prettier',
    rootMarkers = {'package.json'},
  },
}

nvim_lsp.efm.setup({
  on_attach = on_attach,
  cmd = {'efm-langserver', '-logfile', '/tmp/efm.log', '-loglevel', '5'},
  init_options = {
    documentFormatting = true,
  },
  filetypes = {'typescript', 'typescriptreact'},
  settings = {
    rootMarkers = {'.git/'},
    languages = {
      typescript = {efm_formatters.prettier},
      typescriptreact = {efm_formatters.prettier},
    },
  },
})

nvim_lsp.tsserver.setup({
  on_attach = function(client)
    client.resolved_capabilities.document_formatting = false

    on_attach(client)
  end,
})
```

**Comment by lukas-reineke** [comment]
I think your timeout for `formatting_sync` is just too short, everything else looks fine.
The default is 100 milliseconds, which is really low.
If I set it to a second (`lua vim.lsp.buf.formatting_sync({}, 1000)`) your config works for me.

**Comment by gbrlsnchs** [comment]
@lukas-reineke That might be it then. All formatters worked fine with the default timeout, so it never crossed my mind efm + prettier needed a higher value. Thank you very much!

**Comment by remi-gelinas** [comment]
Odd - I took the setup from @gbrlsnchs's config, and I now see the event populating in the efm log, and the response coming back. Immediately after I get the response though, the request seems to get cancelled:

```
2021/02/10 10:55:14 jsonrpc2 handler: notification "$/cancelRequest" handling error: jsonrpc2: code -32601 message: method not supported: $/cancelRequest
```

I'm using the one second timeout you suggested @lukas-reineke - maybe it's still not enough?

**Comment by jrock2004** [comment]
I had to go to a 1500 timeout

**Comment by bradcush** [comment]
Both async and sync formatting work fine for me except the input passed to prettier in this case is only what's been saved so running the formatting before save ends up replacing the entire buffer with and saving the file without any changes. Am I missing something to have the unsaved contents of the buffer used? My setup is a bit different but quite similar to the above, I'm just using a config file with efm instead.

**Comment by gbrlsnchs** [comment]
> Both async and sync formatting work fine for me except the input passed to prettier in this case is only what's been saved so running the formatting before save ends up replacing the entire buffer with and saving the file without any changes. Am I missing something to have the unsaved contents of the buffer used? My setup is a bit different but quite similar to the above, I'm just using a config file with efm instead.

Yeah, I have noticed that too. Other LSP servers like rust-analyzer format unsaved buffer correctly. It might be worth opening a new issue in order to specifically track that issue.

**Comment by lukas-reineke** [comment]
> Both async and sync formatting work fine for me except the input passed to prettier in this case is only what's been saved so running the formatting before save ends up replacing the entire buffer with and saving the file without any changes. Am I missing something to have the unsaved contents of the buffer used? My setup is a bit different but quite similar to the above, I'm just using a config file with efm instead.

Please open a new issue, this is not related to the original issue here.
Also, most likely your issue is a mistake in the configuration. It does not matter to EFM if the buffer is saved or not.
