### ISSUE TITLE
Global initialization options vs local capabilities

### ISSUE THREAD

**Issue by alexaandru** [mattn/efm-langserver#96]
The initialization options (i.e. `init_options` in here https://github.com/mattn/efm-langserver#configuration-for-neovim-buildin-lsp-with-nvim-lspconfig) are global (i.e. you specify globally for efm config whether it supports document formatting, for example) however the actual capability is local to the language.

More concretely:

I use `efm` to format lua AND to lint go code. I DO want the documentFormatting capability to be true for the lua LSP server, however I want the same capability to be false for the go/efm LSP server, since I also use `gopls` and I want that one to handle the formatting, not both. The problem is, I can only set that setting once per efm config, not for each language individually.

What am I missing? Doesn't it make more sense to have those capabilities defined locally (and even better, inferred - i.e., if I define a format command, then turn on documentFormatting capability for THAT particular language)?

**Comment by cloggier** [comment]
Related https://github.com/mattn/efm-langserver/issues/87

**Comment by alexaandru** [comment]
Been thinking a bit more about it, `efm` is actually just one single LSP server supporting all the configured languages (vs. many LSPs, one for each language). Which makes sense why those init options are global for efm...  I guess I'll have to find some other workaround.

**Comment by alexaandru** [comment]
Closing this as 1) the issue makes no sense after some more thought, this is just one LSP server, so of course it can only have one initialization and 2) I've solved my issue from `on_attach()` handler, disabling formatting for `go` when it comes from `efm`:

```Lua
local function on_attach(client, bufnr)
  local okFmt = client.name ~= "efm" or vim.fn.getbufvar(bufnr, "&filetype") ~= "go"
  if okFmt and client.resolved_capabilities.document_formatting then
    vim.cmd("au Setup BufWritePre <buffer> lua vim.lsp.buf.formatting()")
  end
end
```
this way, I only get formatting from `gopls` for `go` and continue to get formatting from `efm` for `lua`. Problem solved :)
